#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           HL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Big Baba's Big Robot
 while(true)
  {
    if(vexRT[Btn6U]==true)
    {//Lift Up
    	motor[LL] = 127;
    	motor[HL] = -127;
    }
    if(vexRT[Btn6U]==false)
    {//Neutralize
    	motor[LL] = 0;
    	motor[HL] = 0;
    }
    if(vexRT[Btn6D]==true)
    {//Lift Down
    	motor[LL] = -127;
    	motor[HL] = 127;
    }
    if(vexRT[Btn6D]==false)
    {//Neutralize
    	motor[LL] = 0;
    	motor[HL] = 0;
    }
    //X-Drive
    motor[FL] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[FR] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[BR] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
    motor[BL] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
 }
}
